spring.application.name=hospitalManagementSystem

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalManagementSystem
spring.datasource.username=postgres
spring.datasource.password=root

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init-location=classpath:data.sql